# Reglas de Negocio - Colsubsidio UES Crédito (FRAMEWORK CONCEPTUAL)
# Este archivo contiene framework estratégico para el modelo de fuga

# =============================================================================
# INFORMACIÓN CORPORATIVA
# =============================================================================



company:
  name: "Caja Colombiana de Subsidio Familiar - Colsubsidio"
  unit: "UES Crédito"
  country: "Colombia"
  currency: "COP"

customer_value:
  avg_annual_value: 2500000
  value_by_segment:
    "Segmento_Alto": 5000000
    "Segmento_Medio": 3000000
    "Segemnto_Basico": 2000000
    "Segmento_Joven": 1500000
  lifetime_multiplier: 3.5
  churn_impact_factor: 0.8

success_metrics:
  model_performance:
    min_auc_roc: 0.75
    target_precision_at_10: 0.15
    max_false_positive_rate: 0.1
  business_targets:
    churn_reduction: 0.20
    min_roi: 3.0
    max_campaign_budget: 500000000
  monitoring_kpis:
    monthly_churn_rate: 0.028
    customer_lifetime_value: 8750000
    retention_cost_per_customer: 75000